// src/utils/icons.js
export const icons = {
  // Emojis (always available)
  cake: "🎂",
  balloons: "🎈",
  heart: "❤️",
  mail: "💌",
  smartphone: "📱",
  zap: "⚡",
  cloudRain: "🌧️",
  music: "🎵",
  gift: "🎁",
  sparkles: "✨",
  star: "⭐",
  sun: "☀️",
  moon: "🌙",
  coffee: "☕",
  globe: "🌍",
  smile: "😊",
  frown: "😔",
  lock: "🔒",
  unlock: "🔓",
  home: "🏠",
  image: "🖼️",
  settings: "⚙️",
  camera: "📷",
  bell: "🔔",
  search: "🔍",
  check: "✅",
  x: "❌",
  plus: "➕",
  minus: "➖",
  play: "▶️",
  pause: "⏸️",
  stop: "⏹️",
  volume: "🔊",
  mute: "🔇",
  heartOutline: "🤍",
  heartFill: "❤️",
  fire: "🔥",
  trophy: "🏆",
  crown: "👑",
  rocket: "🚀",
  party: "🎉",
  confetti: "🎊",
  rainbow: "🌈",
  flower: "🌸",
  leaf: "🍃",
  sunWithFace: "🌞",
  moonWithFace: "🌝",
  star2: "🌟",
  comet: "☄️",
  snowflake: "❄️",
  umbrella: "☂️",
  thunder: "⛈️",
  wind: "💨",
  wave: "🌊",
  mountain: "⛰️",
  tree: "🌳",
  palm: "🌴",
  cactus: "🌵",
  earth: "🌎",
  flag: "🎌",
  map: "🗺️",
  compass: "🧭",
  clock: "⏰",
  hourglass: "⏳",
  calendar: "📅",
  gift2: "🎁",
  balloon2: "🎈",
  ribbon: "🎀",
  ticket: "🎫",
  medal: "🏅",
  diamond: "💎",
  gem: "💍",
  money: "💰",
  coin: "🪙",
  key: "🔑",
  lockWithKey: "🗝️",
  lightbulb: "💡",
  battery: "🔋",
  plug: "🔌",
  tool: "🛠️",
  magnet: "🧲",
  puzzle: "🧩",
  game: "🎮",
  dice: "🎲",
  chess: "♟️",
  cards: "🃏",
  arts: "🎨",
  microphone: "🎤",
  headphones: "🎧",
  film: "🎞️",
  clapper: "🎬",
  theater: "🎭",
  book: "📖",
  newspaper: "📰",
  notebook: "📓",
  pen: "🖊️",
  pencil: "✏️",
  paint: "🖌️",
  scissors: "✂️",
  paperclip: "📎",
  link: "🔗",
  inbox: "📥",
  outbox: "📤",
  envelope: "✉️",
  email: "📧",
  phone: "📞",
  mobile: "📱",
  computer: "💻",
  printer: "🖨️",
  keyboard: "⌨️",
  mouse: "🖱️",
  trackpad: "🖲️",
  disk: "💾",
  cd: "💿",
  dvd: "📀",
  tv: "📺",
  radio: "📻",
  video: "📹",
  camera2: "📸",
  flashlight: "🔦",
  lantern: "🏮",
  candle: "🕯️",
  bulb: "💡",

  // Custom combinations
  heartRain: "❤️🌧️",
  birthday: "🎂🎉",
  loveLetter: "💌❤️",
  phoneShake: "📱🌀",
  balloonPop: "🎈💥",
  cakeSlice: "🎂🔪",
  cloudHeart: "☁️❤️",
  starRain: "⭐🌧️",
  magic: "✨🔮",

  // Navigation icons
  arrowLeft: "⬅️",
  arrowRight: "➡️",
  arrowUp: "⬆️",
  arrowDown: "⬇️",
  back: "↩️",
  forward: "↪️",
  upDown: "↕️",
  leftRight: "↔️",
  refresh: "🔄",
  reload: "↪️",
  close: "❌",
  menu: "☰",
  hamburger: "🍔",
  list: "📋",
  grid: "🔳",
  layout: "📐",

  // Status icons
  success: "✅",
  error: "❌",
  warning: "⚠️",
  info: "ℹ️",
  question: "❓",
  help: "❔",
  exclamation: "❗",
  loading: "⏳",
  done: "🏁",
  progress: "📈",
  chart: "📊",

  // Weather
  sunny: "☀️",
  cloudy: "☁️",
  partlySunny: "⛅",
  rainy: "🌧️",
  thunderstorm: "⛈️",
  snowy: "❄️",
  windy: "💨",
  tornado: "🌪️",
  foggy: "🌫️",

  // Faces
  happy: "😊",
  sad: "😢",
  angry: "😠",
  laughing: "😂",
  cool: "😎",
  wink: "😉",
  kiss: "😘",
  love: "🥰",
  sleepy: "😴",
  sick: "🤒",
  surprised: "😲",
  thinking: "🤔",
  shush: "🤫",
  celebration: "🥳",
};

// Utility function to get icon with size
export const getIcon = (name, size = "text-2xl") => {
  return `<span class="${size}">${icons[name] || "❓"}</span>`;
};

// Component for React
export const Icon = ({ name, className = "", size = 24 }) => {
  return (
    <span className={`inline-block ${className}`} style={{ fontSize: size }}>
      {icons[name] || "❓"}
    </span>
  );
};
